package me.flamboyant.manhunt.roles;

public enum ManhuntRoleIdentifier {
    // Bad design but f*ck : Names must start with corresponding ManhuntRoleType
    HUNTER_SIMPLE,
    HUNTER_CHECKPOINT,
    HUNTER_CUTCLEAN,
    HUNTER_LINK,
    HUNTER_PRO_MINER,
    HUNTER_ELF,
    SPEEDRUNNER_SIMPLE,
    SPEEDRUNNER_CUTCLEAN,
    SPEEDRUNNER_SWAPPER,
    SPEEDRUNNER_LINK,
    SPEEDRUNNER_CHECKPOINT,
    SPEEDRUNNER_ELF,
    SPEEDRUNNER_WEREWOLF,
    SPEEDRUNNER_TNT_TACTICAL,
    ALLY_IMPOSTER,
    SUPER_HUNTER,
    NEUTRAL_GLUER,
    NEUTRAL_UNDECIDED
}
